# Generated by Django 4.0.3 on 2022-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('user_id', models.CharField(default='null', max_length=20)),
                ('item_name', models.CharField(max_length=20)),
                ('item_id', models.CharField(max_length=20)),
                ('item_rate', models.CharField(max_length=20)),
                ('item_quantity', models.CharField(max_length=2)),
                ('order_cost', models.CharField(max_length=20)),
            ],
        ),
    ]
