# Generated by Django 4.0.3 on 2022-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='f_print',
            field=models.TextField(default='null'),
        ),
    ]
